/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.70
 * Generated at: 2017-10-10 02:21:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class grzx_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <title>无线点餐后台</title>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"/SSMPropertys/bootstrap/css/bootstrap.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"/SSMPropertys/css/theme.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/SSMPropertys/font-awesome/css/font-awesome.css\">\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"/SSMPropertys/js/jquery-1.7.2.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <script src=\"/SSMPropertys/bootstrap/js/bootstrap.js\"></script>\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("    <!-- Demo page code -->\r\n");
      out.write("\r\n");
      out.write("    <style type=\"text/css\">\r\n");
      out.write("        #line-chart {\r\n");
      out.write("            height:300px;\r\n");
      out.write("            width:800px;\r\n");
      out.write("            margin: 0px auto;\r\n");
      out.write("            margin-top: 1em;\r\n");
      out.write("        }\r\n");
      out.write("        .brand { font-family: georgia, serif; }\r\n");
      out.write("        .brand .first {\r\n");
      out.write("            color: #ccc;\r\n");
      out.write("            font-style: italic;\r\n");
      out.write("        }\r\n");
      out.write("        .brand .second {\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("  </head>\r\n");
      out.write("  <body class=\"\"> \r\n");
      out.write("  <!--<![endif]-->\r\n");
      out.write("    \r\n");
      out.write("        <div class=\"navbar\">\r\n");
      out.write("        <div class=\"navbar-inner\">\r\n");
      out.write("                <ul class=\"nav pull-right\">\r\n");
      out.write("                    \r\n");
      out.write("                    <li><a href=\"#\" class=\"hidden-phone visible-tablet visible-desktop\" role=\"button\">设置</a></li>\r\n");
      out.write("                    <li id=\"fat-menu\" class=\"dropdown\">\r\n");
      out.write("                        <a href=\"#\" role=\"button\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">\r\n");
      out.write("                            <i class=\"icon-user\"></i>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${geren}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\r\n");
      out.write("                            <i class=\"icon-caret-down\"></i>\r\n");
      out.write("                        </a>\r\n");
      out.write("\r\n");
      out.write("                        <ul class=\"dropdown-menu\">\r\n");
      out.write("                            <li><a tabindex=\"-1\" href=\"/SSMPropertys/home.do\" >个人中心</a></li>\r\n");
      out.write("                            <li class=\"divider\"></li>\r\n");
      out.write("                            <li><a tabindex=\"-1\" href=\"/SSMPropertys/login.do\">退出</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    \r\n");
      out.write("                </ul>\r\n");
      out.write("                <a class=\"brand\" href=\"/SSMPropertys/index.do\"><span class=\"first\">无线点餐</span> <span class=\"second\">后台</span></a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"sidebar-nav\">\r\n");
      out.write("        <form class=\"search form-inline\">\r\n");
      out.write("            <input type=\"text\" placeholder=\"Search...\">\r\n");
      out.write("        </form>\r\n");
      out.write("\r\n");
      out.write("        <a href=\"#dashboard-menu\" class=\"nav-header\" data-toggle=\"collapse\"><i class=\"icon-dashboard\"></i>首页</a>\r\n");
      out.write("        <ul id=\"dashboard-menu\" class=\"nav nav-list collapse in\">\r\n");
      out.write("            <li><a href=\"/SSMPropertys/index.do\">报表</a></li>\r\n");
      out.write("            <li><a href=\"/SSMPropertys/grzx.do\">个人中心</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("\r\n");
      out.write("        <a href=\"#table-menu\" class=\"nav-header\" data-toggle=\"collapse\"><i class=\"icon-table\"></i>餐桌\r\n");
      out.write("        </a>\r\n");
      out.write("        <ul id=\"table-menu\" class=\"nav nav-list collapse\">\r\n");
      out.write("            <li ><a href=\"/SSMPropertys/table.do\">餐桌管理</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("\r\n");
      out.write("        <a href=\"#menu-menu\" class=\"nav-header collapsed\" data-toggle=\"collapse\"><i class=\"icon-reorder\"></i>菜谱\r\n");
      out.write("         </a>\r\n");
      out.write("        <ul id=\"menu-menu\" class=\"nav nav-list collapse\">\r\n");
      out.write("            <li ><a href=\"/SSMPropertys/menu.do\">菜谱管理</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("\r\n");
      out.write("        <a href=\"#order-menu\" class=\"nav-header\" data-toggle=\"collapse\"><i class=\"icon-th-large\"></i>订单</a>\r\n");
      out.write("        <ul id=\"order-menu\" class=\"nav nav-list collapse\">\r\n");
      out.write("            <li ><a href=\"/SSMPropertys/order.do\">订单管理</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    <!-- 内容 开始 -->\r\n");
      out.write("   <div class=\"content\">\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"header\">\r\n");
      out.write("            \r\n");
      out.write("            <h1 class=\"page-title\">个人中心</h1>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("                <ul class=\"breadcrumb\">\r\n");
      out.write("            <li><a href=\"/SSMPropertys/home.do?flag=home\">主页</a> <span class=\"divider\">/</span></li>\r\n");
      out.write("            <li class=\"active\">个人中心</li>\r\n");
      out.write("        </ul>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"container-fluid\">\r\n");
      out.write("            <div class=\"row-fluid\">\r\n");
      out.write("            \r\n");
      out.write("         <form id=\"tab\" action=\"/SSMPropertys/refresh.do\" method=\"post\">               \r\n");
      out.write("\t\t\t<div class=\"btn-toolbar\">\r\n");
      out.write("    \t\t\t<button class=\"btn btn-primary\"><i class=\"icon-save\"></i> 保存</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t<div class=\"well\">\r\n");
      out.write("    <ul class=\"nav nav-tabs\">\r\n");
      out.write("      <li class=\"active\"><a href=\"#home\" data-toggle=\"tab\">基本资料</a></li>\r\n");
      out.write("      <li><a href=\"#profile\" data-toggle=\"tab\">密码更改</a></li>\r\n");
      out.write("    </ul>\r\n");
      out.write("    <div id=\"myTabContent\" class=\"tab-content\">\r\n");
      out.write("      <div class=\"tab-pane active in\" id=\"home\">\r\n");
      out.write("\r\n");
      out.write("        <label>用户id</label>\r\n");
      out.write("        <input name=\"uid\" type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${usertbl.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" class=\"input-xlarge uneditable-input\">\r\n");
      out.write("        <label>用户名</label>\r\n");
      out.write("        <input name=\"uname\"  type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${usertbl.username}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" class=\"input-xlarge\">\r\n");
      out.write("        <label>真实姓名</label>\r\n");
      out.write("        <input  name=\"name\"  type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${usertbl.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" class=\"input-xlarge\">\r\n");
      out.write("        <label>性别</label>\r\n");
      out.write("        <input name=\"gender\"  type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${usertbl.gender}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" class=\"input-xlarge\">\r\n");
      out.write("        <label>权限</label>\r\n");
      out.write("        <input name=\"permission\"  type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${usertbl.permission}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" class=\"input-xlarge\">\r\n");
      out.write("        <label>备注</label>\r\n");
      out.write("        <input name=\"remark\"  type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${usertbl.remark}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" class=\"input-xlarge\">\r\n");
      out.write("        \r\n");
      out.write("    </form>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"tab-pane fade\" id=\"profile\">\r\n");
      out.write("    <form id=\"tab2\" action=\"/SSMPropertys/save.do\" method=\"post\">\r\n");
      out.write("    \t<input type=\"hidden\" name=\"uname\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${usertbl.username}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("        <label>新密码</label>\r\n");
      out.write("        <input name=\"password\" type=\"password\" class=\"input-xlarge\">\r\n");
      out.write("        <div>\r\n");
      out.write("            <button class=\"btn btn-primary\">更改</button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </form>\r\n");
      out.write("      </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("                    \r\n");
      out.write("                  <footer>\r\n");
      out.write("                        <hr>\r\n");
      out.write("                        <p class=\"pull-right\">&copy; 2013.8 <a href=\"http://www.52itstyle.com\" target=\"_blank\"> shun_fzll</a></p>\r\n");
      out.write("                    </footer>\r\n");
      out.write("                    \r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("        $(\"[rel=tooltip]\").tooltip();\r\n");
      out.write("        $(function() {\r\n");
      out.write("            $('.demo-cancel-click').click(function(){return false;});\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
